[project]
name = "streamlit-llm-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shyamjith", email = "shyamjithsmaniyoor@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "argon2-cffi>=25.1.0",
    "dotenv>=0.9.9",
    "langchain>=0.3.30",
    "langchain-community>=0.3.31",
    "langchain-groq>=0.3.8",
    "langchain-openai>=0.3.35",
    "langchain-tavily>=0.2.11",
    "langgraph>=0.6.11",
    "neon-api>=0.3.0",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.50.0",
    "streamlit-cookies-controller>=0.0.4",
    "watchdog>=6.0.0",
]

[project.scripts]
streamlit-llm-rag = "streamlit_llm_rag:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
extraPaths = ["."]

[tool.uv]
package = false

